#!/usr/bin/env bash
# out/ altındaki Foundry artefaktlarından ABI'leri backend (JSON) ve app (TS, `as const`) dizinlerine yazar.
# Kullanım: contracts/scripts/export-abi.sh   (veya `make abi`)
set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/.foundry/bin:$PATH"

command -v jq >/dev/null || { echo "jq gerekli (brew install jq)"; exit 1; }

forge build

BE=../backend/app/services/chain/abi
FE=../app/src/lib/chain/abi
mkdir -p "$BE" "$FE"

HEADER="// AUTO-GENERATED by contracts/scripts/export-abi.sh — do not edit"

# Backend: kontrat başına ABI JSON'u
for C in TraderVault MockRouter TestToken; do
  jq '.abi' "out/$C.sol/$C.json" > "$BE/$C.json"
done
# ERC-20: OZ IERC20Metadata (IERC20 + name/symbol/decimals)
jq '.abi' out/IERC20Metadata.sol/IERC20Metadata.json > "$BE/IERC20.json"

# Frontend: viem uyumlu `as const` sabitleri
{
  echo "$HEADER"
  echo "export const traderVaultAbi = $(jq -c '.abi' out/TraderVault.sol/TraderVault.json) as const;"
} > "$FE/traderVault.ts"
{
  echo "$HEADER"
  echo "export const erc20Abi = $(jq -c '.abi' out/IERC20Metadata.sol/IERC20Metadata.json) as const;"
} > "$FE/erc20.ts"

echo "ABI yazıldı:"
ls -1 "$BE"/TraderVault.json "$BE"/MockRouter.json "$BE"/TestToken.json "$BE"/IERC20.json "$FE"/traderVault.ts "$FE"/erc20.ts
