"""init — TraderKirala schema (DESIGN.md §2.1 / §3.2), 20 tables.

Revision ID: a780a7ffa848
Revises: 
Create Date: 2026-09-19 16:03:27.794251+00:00
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = 'a780a7ffa848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('contract_id', sa.String(length=56), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('issuer', sa.String(length=56), nullable=True),
    sa.Column('decimals', sa.Integer(), server_default='7', nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('crypto', 'stable_fx', 'defi', name='marketcategory', native_enum=False, length=32), nullable=False),
    sa.Column('is_base_allowed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('onchain_allowed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('network', 'contract_id', name='uq_assets_network_contract_id')
    )
    op.create_index('ix_assets_network_code', 'assets', ['network', 'code'], unique=False)
    op.create_table('auth_nonces',
    sa.Column('public_key', sa.String(length=56), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_nonces')),
    sa.UniqueConstraint('nonce', name=op.f('uq_auth_nonces_nonce'))
    )
    op.create_index(op.f('ix_auth_nonces_public_key'), 'auth_nonces', ['public_key'], unique=False)
    op.create_table('indexer_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('cursor', sa.String(length=128), nullable=True),
    sa.Column('ledger', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_indexer_state'))
    )
    op.create_table('users',
    sa.Column('stellar_address', sa.String(length=56), nullable=False),
    sa.Column('role', sa.Enum('customer', 'trader', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('risk_profile', sa.Enum('conservative', 'balanced', 'aggressive', name='riskprofile', native_enum=False, length=32), nullable=True),
    sa.Column('markets', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('strategy_summary', sa.Text(), nullable=True),
    sa.Column('commission_bps', sa.Integer(), nullable=True),
    sa.Column('min_capital', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel', native_enum=False, length=32), nullable=True),
    sa.Column('expo_push_token', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_return_bps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('monthly_return_bps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_drawdown_bps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('win_rate_bps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('managed_capital', sa.Numeric(precision=30, scale=7), server_default='0', nullable=False),
    sa.Column('active_agreements', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_stellar_address'), 'users', ['stellar_address'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('anchor_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_domain', sa.String(length=255), nullable=False),
    sa.Column('account', sa.String(length=56), nullable=False),
    sa.Column('jwt', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_anchor_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anchor_sessions')),
    sa.UniqueConstraint('user_id', 'anchor_domain', name='uq_anchor_sessions_user_domain')
    )
    op.create_table('anchor_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_domain', sa.String(length=255), nullable=False),
    sa.Column('anchor_tx_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('deposit', 'withdraw', name='anchortxkind', native_enum=False, length=16), nullable=False),
    sa.Column('asset_code', sa.String(length=12), nullable=False),
    sa.Column('asset_issuer', sa.String(length=56), nullable=True),
    sa.Column('amount_in', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('amount_out', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('amount_fee', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='incomplete', nullable=False),
    sa.Column('interactive_url', sa.Text(), nullable=True),
    sa.Column('more_info_url', sa.Text(), nullable=True),
    sa.Column('withdraw_anchor_account', sa.String(length=69), nullable=True),
    sa.Column('withdraw_memo', sa.String(length=128), nullable=True),
    sa.Column('withdraw_memo_type', sa.String(length=16), nullable=True),
    sa.Column('stellar_tx_hash', sa.String(length=64), nullable=True),
    sa.Column('external_tx_id', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_anchor_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anchor_transactions')),
    sa.UniqueConstraint('anchor_domain', 'anchor_tx_id', name='uq_anchor_transactions_domain_tx_id')
    )
    op.create_index('ix_anchor_transactions_status', 'anchor_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_anchor_transactions_stellar_tx_hash'), 'anchor_transactions', ['stellar_tx_hash'], unique=False)
    op.create_index('ix_anchor_transactions_user_created', 'anchor_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('trader_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['users.id'], name=op.f('fk_follows_trader_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'trader_id', name=op.f('pk_follows'))
    )
    op.create_index(op.f('ix_follows_trader_id'), 'follows', ['trader_id'], unique=False)
    op.create_table('interactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('listing', 'user', name='interactiontargettype', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('pass_', 'like', 'save', 'follow', 'view', 'offer_request', name='interactionaction', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions')),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', 'action', name='uq_interactions_user_target_action')
    )
    op.create_index('ix_interactions_target', 'interactions', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('capital', 'service', name='listingkind', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('risk_profile', sa.Enum('conservative', 'balanced', 'aggressive', name='riskprofile', native_enum=False, length=32), nullable=True),
    sa.Column('markets', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'closed', name='listingstatus', native_enum=False, length=32), server_default='active', nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('base_asset_id', sa.UUID(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('max_loss_bps', sa.Integer(), nullable=True),
    sa.Column('commission_bps', sa.Integer(), nullable=True),
    sa.Column('min_capital', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('expected_return_min_bps', sa.Integer(), nullable=True),
    sa.Column('expected_return_max_bps', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('offer_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], name=op.f('fk_listings_base_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_listings_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings'))
    )
    op.create_index('ix_listings_kind_status_created', 'listings', ['kind', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('listing', 'offer', 'agreement', 'wallet', 'system', name='notificationcategory', native_enum=False, length=32), server_default='system', nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_category', 'notifications', ['user_id', 'category'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_favorites_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'listing_id', name=op.f('pk_favorites'))
    )
    op.create_index(op.f('ix_favorites_listing_id'), 'favorites', ['listing_id'], unique=False)
    op.create_table('offers',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('trader_to_customer', 'customer_to_trader', name='offerdirection', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=7), nullable=False),
    sa.Column('base_asset_id', sa.UUID(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('commission_bps', sa.Integer(), nullable=False),
    sa.Column('max_drawdown_bps', sa.Integer(), server_default='10000', nullable=False),
    sa.Column('expected_return_min_bps', sa.Integer(), nullable=True),
    sa.Column('expected_return_max_bps', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'withdrawn', 'expired', name='offerstatus', native_enum=False, length=32), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreement_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], name=op.f('fk_offers_base_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_offers_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_offers_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_offers_to_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index('ix_offers_from_user_status', 'offers', ['from_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_offers_listing_id'), 'offers', ['listing_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index('ix_offers_to_user_status', 'offers', ['to_user_id', 'status'], unique=False)
    op.create_table('agreements',
    sa.Column('onchain_id', sa.BigInteger(), nullable=True),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('trader_id', sa.UUID(), nullable=False),
    sa.Column('base_asset_id', sa.UUID(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=30, scale=7), nullable=False),
    sa.Column('duration_secs', sa.BigInteger(), nullable=False),
    sa.Column('commission_bps', sa.Integer(), nullable=False),
    sa.Column('max_drawdown_bps', sa.Integer(), nullable=False),
    sa.Column('risk_profile', sa.Enum('conservative', 'balanced', 'aggressive', name='riskprofile', native_enum=False, length=32), nullable=True),
    sa.Column('listing_ref', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'proposed', 'funded', 'active', 'settled', 'cancelled', 'failed', name='agreementstatus', native_enum=False, length=32), server_default='draft', nullable=False),
    sa.Column('proposer_role', sa.Enum('customer', 'trader', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('created_tx', sa.String(length=64), nullable=True),
    sa.Column('activate_tx', sa.String(length=64), nullable=True),
    sa.Column('cancel_tx', sa.String(length=64), nullable=True),
    sa.Column('settle_tx', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('value_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('high_water_value', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('final_value', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('profit', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('trader_fee', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('customer_payout', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_by', sa.String(length=56), nullable=True),
    sa.Column('last_event_ledger', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], name=op.f('fk_agreements_base_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_agreements_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_agreements_listing_id_listings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_agreements_offer_id_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trader_id'], ['users.id'], name=op.f('fk_agreements_trader_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agreements')),
    sa.UniqueConstraint('onchain_id', name=op.f('uq_agreements_onchain_id'))
    )
    op.create_index('ix_agreements_customer_status', 'agreements', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_agreements_listing_id'), 'agreements', ['listing_id'], unique=False)
    op.create_index(op.f('ix_agreements_offer_id'), 'agreements', ['offer_id'], unique=False)
    op.create_index(op.f('ix_agreements_status'), 'agreements', ['status'], unique=False)
    op.create_index('ix_agreements_trader_status', 'agreements', ['trader_id', 'status'], unique=False)
    # offers.agreement_id <-> agreements.offer_id cycle: this side is added once both tables exist
    op.create_foreign_key('fk_offers_agreement_id_agreements', 'offers', 'agreements', ['agreement_id'], ['id'], ondelete='SET NULL')
    op.create_table('agreement_balances',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=30, scale=7), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_agreement_balances_agreement_id_agreements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_agreement_balances_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('agreement_id', 'asset_id', name=op.f('pk_agreement_balances'))
    )
    op.create_table('agreement_value_snapshots',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=7), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_agreement_value_snapshots_agreement_id_agreements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agreement_value_snapshots'))
    )
    op.create_index('ix_agreement_value_snapshots_agreement_at', 'agreement_value_snapshots', ['agreement_id', 'at'], unique=False)
    op.create_table('conversations',
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('agreement_id', sa.UUID(), nullable=True),
    sa.Column('participant_a', sa.UUID(), nullable=False),
    sa.Column('participant_b', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_conversations_agreement_id_agreements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_conversations_offer_id_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_a'], ['users.id'], name=op.f('fk_conversations_participant_a_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_b'], ['users.id'], name=op.f('fk_conversations_participant_b_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('agreement_id', name=op.f('uq_conversations_agreement_id')),
    sa.UniqueConstraint('offer_id', name=op.f('uq_conversations_offer_id'))
    )
    op.create_index('ix_conversations_participant_a', 'conversations', ['participant_a'], unique=False)
    op.create_index('ix_conversations_participant_b', 'conversations', ['participant_b'], unique=False)
    op.create_table('pending_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('open', 'propose', 'fund', 'accept', 'cancel', 'trade', 'settle', 'payment', 'trustline', 'admin', name='pendingtxkind', native_enum=False, length=32), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=True),
    sa.Column('unsigned_xdr', sa.Text(), nullable=False),
    sa.Column('tx_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('built', 'submitted', 'success', 'failed', 'expired', name='pendingtxstatus', native_enum=False, length=32), server_default='built', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_pending_transactions_agreement_id_agreements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pending_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_transactions'))
    )
    op.create_index(op.f('ix_pending_transactions_agreement_id'), 'pending_transactions', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_pending_transactions_status'), 'pending_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_pending_transactions_tx_hash'), 'pending_transactions', ['tx_hash'], unique=False)
    op.create_index('ix_pending_transactions_user_created', 'pending_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('ratings',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('trader_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name=op.f('ck_ratings_score_range')),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_ratings_agreement_id_agreements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_ratings_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['users.id'], name=op.f('fk_ratings_trader_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('agreement_id', name=op.f('uq_ratings_agreement_id'))
    )
    op.create_index(op.f('ix_ratings_trader_id'), 'ratings', ['trader_id'], unique=False)
    op.create_table('trades',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('onchain_seq', sa.BigInteger(), nullable=True),
    sa.Column('tx_hash', sa.String(length=64), nullable=True),
    sa.Column('ledger', sa.BigInteger(), nullable=True),
    sa.Column('trader_id', sa.UUID(), nullable=True),
    sa.Column('token_in_id', sa.UUID(), nullable=False),
    sa.Column('token_out_id', sa.UUID(), nullable=False),
    sa.Column('amount_in', sa.Numeric(precision=30, scale=7), nullable=False),
    sa.Column('amount_out', sa.Numeric(precision=30, scale=7), nullable=False),
    sa.Column('value_after', sa.Numeric(precision=30, scale=7), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('symbol_label', sa.String(length=60), nullable=True),
    sa.Column('notify_investors', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_trades_agreement_id_agreements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_in_id'], ['assets.id'], name=op.f('fk_trades_token_in_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['token_out_id'], ['assets.id'], name=op.f('fk_trades_token_out_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trader_id'], ['users.id'], name=op.f('fk_trades_trader_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('tx_hash', 'onchain_seq', name='uq_trades_tx_hash_onchain_seq')
    )
    op.create_index('ix_trades_agreement_created', 'trades', ['agreement_id', 'created_at'], unique=False)
    op.create_index('ix_trades_trader_created', 'trades', ['trader_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_trades_tx_hash'), 'trades', ['tx_hash'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_offers_agreement_id_agreements', 'offers', type_='foreignkey')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_trades_tx_hash'), table_name='trades')
    op.drop_index('ix_trades_trader_created', table_name='trades')
    op.drop_index('ix_trades_agreement_created', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_ratings_trader_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('ix_pending_transactions_user_created', table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_tx_hash'), table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_status'), table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_agreement_id'), table_name='pending_transactions')
    op.drop_table('pending_transactions')
    op.drop_index('ix_conversations_participant_b', table_name='conversations')
    op.drop_index('ix_conversations_participant_a', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_agreement_value_snapshots_agreement_at', table_name='agreement_value_snapshots')
    op.drop_table('agreement_value_snapshots')
    op.drop_table('agreement_balances')
    op.drop_index('ix_agreements_trader_status', table_name='agreements')
    op.drop_index(op.f('ix_agreements_status'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_offer_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_listing_id'), table_name='agreements')
    op.drop_index('ix_agreements_customer_status', table_name='agreements')
    op.drop_table('agreements')
    op.drop_index('ix_offers_to_user_status', table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_listing_id'), table_name='offers')
    op.drop_index('ix_offers_from_user_status', table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_favorites_listing_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_notifications_user_category', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_index('ix_listings_kind_status_created', table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index('ix_interactions_target', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_follows_trader_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index('ix_anchor_transactions_user_created', table_name='anchor_transactions')
    op.drop_index(op.f('ix_anchor_transactions_stellar_tx_hash'), table_name='anchor_transactions')
    op.drop_index('ix_anchor_transactions_status', table_name='anchor_transactions')
    op.drop_table('anchor_transactions')
    op.drop_table('anchor_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_stellar_address'), table_name='users')
    op.drop_table('users')
    op.drop_table('indexer_state')
    op.drop_index(op.f('ix_auth_nonces_public_key'), table_name='auth_nonces')
    op.drop_table('auth_nonces')
    op.drop_index('ix_assets_network_code', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
